document.write( '<div class=\"footer-wrapper\">\n' );
document.write( '            <div class=\"container-fluid\">\n' );
document.write( '                <div class=\"row\">\n' );
document.write( '                    <div class=\"col-sm-6\">\n' );
document.write( '                        <ul class=\"nav copyright\">\n' );
document.write( '                            <li class=\"nav-item footer-logo\">\n' );
document.write( '                                <a class=\"nav-link disabled\" href=\"#\"><img src=\"images/footer-copyright-logo.png\" alt=\"\"></a>\n' );
document.write( '                            </li>\n' );
document.write( '                            <li class=\"nav-item\">\n' );
document.write( '                                <a class=\"nav-link disabled\" href=\"#\">© PARK DIRECT</a>\n' );
document.write( '                            </li>\n' );
document.write( '                            <li class=\"nav-item\">\n' );
document.write( '                                <a class=\"nav-link disabled\" href=\"#\">サポート/ver.1.0.0</a>\n' );
document.write( '                            </li>\n' );
document.write( '                        </ul>\n' );
document.write( '                    </div>\n' );
document.write( '                    <div class=\"col-sm-6\">\n' );
document.write( '                        <ul class=\"nav justify-content-sm-end footer-nav\">\n' );
document.write( '                            <li class=\"nav-item\">\n' );
document.write( '                                <a class=\"nav-link\" href=\"#\">利用規約</a>\n' );
document.write( '                            </li>\n' );
document.write( '                            <li class=\"nav-item\">\n' );
document.write( '                                <a class=\"nav-link\" href=\"#\">プライバシーポリシー</a>\n' );
document.write( '                            </li>\n' );
document.write( '                            <li class=\"nav-item\">\n' );
document.write( '                                <a class=\"nav-link\" href=\"#\">サポート/フィードバック</a>\n' );
document.write( '                            </li>\n' );
document.write( '                        </ul>\n' );
document.write( '                    </div>\n' );
document.write( '                </div>\n' );
document.write( '            </div>\n' );
document.write( '        </div>' );
